package View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Manfred Armijos
 */
public class ViewPort extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewPort() {
        initComponents();
    }

    public JButton getBtnGoMenu() {
        return btnGoMenu;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public String getTypeForm() {
        return cbxType.getSelectedItem().toString();
    }
    
    
    
    public String getCategoryForm() {
        return cbxCategory.getSelectedItem().toString();
    }
    
    /*
    SHOW ERRORS
    */
    
    public void showErrorCategory() {
        lblErrorCategory.setText("please select one");
    }

    public void showlErrorName() {
        lblErrorName.setText("invalid name");
    }

    public void showErrorQuantity() {
        lblErrorQuantity.setText("invalid quantity");
    }

    public void showErrorType() {
        lblErrorType.setText("please select one");
    }
    
    /*
    CLEAN ERRORS
    */
    
    public void cleanErrorCategory() {
        lblErrorCategory.setText("");
    }

    public void cleanlErrorName() {
        lblErrorName.setText("");
    }

    public void cleanErrorQuantity() {
        lblErrorQuantity.setText("");
    }

    public void cleanErrorType() {
        lblErrorType.setText("");
    }
    

    public String getIMO() {
        return txfIMO.getSelectedText();
    }

    public String getTxfName() {
        return txfName.getSelectedText();
    }

    public String getTxfSearch() {
        return txfSearch.getSelectedText();
    }

    public String getTxfQuantity() {
        return txfQuantity.getSelectedText();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txfName = new javax.swing.JTextField();
        lblErrorName = new javax.swing.JLabel();
        lblErrorCategory = new javax.swing.JLabel();
        txfQuantity = new javax.swing.JTextField();
        cbxCategory = new javax.swing.JComboBox<>();
        cbxType = new javax.swing.JComboBox<>();
        txfIMO = new javax.swing.JTextField();
        lblErrorIMO = new javax.swing.JLabel();
        lblErrorType = new javax.swing.JLabel();
        lblErrorQuantity = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnGoMenu = new javax.swing.JButton();
        txfSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblFormTitle.setText("VESSEL FORM");
        jPanel2.add(lblFormTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        btnSave.setBackground(new java.awt.Color(0, 193, 212));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSave.setText("SAVE");
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 200, 50));

        txfName.setBackground(new java.awt.Color(30, 40, 53));
        txfName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName.setForeground(new java.awt.Color(255, 255, 255));
        txfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(txfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        lblErrorName.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 440, 20));

        lblErrorCategory.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 440, 20));

        txfQuantity.setBackground(new java.awt.Color(30, 40, 53));
        txfQuantity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfQuantity.setForeground(new java.awt.Color(255, 255, 255));
        txfQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Quantity", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfQuantity.setCaretColor(new java.awt.Color(255, 255, 255));
        txfQuantity.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(txfQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        cbxCategory.setBackground(new java.awt.Color(30, 40, 53));
        cbxCategory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxCategory.setForeground(new java.awt.Color(255, 255, 255));
        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "SMALL", "MEDIUM", "LARGE", "EXTRALARGE" }));
        cbxCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxCategory.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxCategory.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(cbxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        cbxType.setBackground(new java.awt.Color(30, 40, 53));
        cbxType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxType.setForeground(new java.awt.Color(255, 255, 255));
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "CRUISE", "CONTAINER" }));
        cbxType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxType.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxType.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(cbxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txfIMO.setBackground(new java.awt.Color(30, 40, 53));
        txfIMO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfIMO.setForeground(new java.awt.Color(255, 255, 255));
        txfIMO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfIMO.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfIMO.setCaretColor(new java.awt.Color(255, 255, 255));
        txfIMO.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(txfIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblErrorIMO.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorIMO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErrorIMO.setToolTipText("");
        jPanel2.add(lblErrorIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 440, 20));

        lblErrorType.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 440, 20));

        lblErrorQuantity.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 440, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 640));

        jPanel3.setBackground(new java.awt.Color(30, 40, 53));
        jPanel3.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(30, 40, 53));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 590, 290));

        jButton1.setBackground(new java.awt.Color(0, 193, 212));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconSearch.png"))); // NOI18N
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, 70));

        jButton3.setBackground(new java.awt.Color(0, 193, 212));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconUpdate.png"))); // NOI18N
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 70));

        jButton4.setBackground(new java.awt.Color(0, 193, 212));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDelete.png"))); // NOI18N
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 70));

        jButton5.setBackground(new java.awt.Color(0, 193, 212));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconClear.png"))); // NOI18N
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, 70));

        btnGoMenu.setBackground(new java.awt.Color(10, 107, 207));
        btnGoMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconExit.png"))); // NOI18N
        btnGoMenu.setBorderPainted(false);
        btnGoMenu.setContentAreaFilled(false);
        jPanel3.add(btnGoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 80, 40));

        txfSearch.setBackground(new java.awt.Color(30, 40, 53));
        txfSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfSearch.setForeground(new java.awt.Color(255, 255, 255));
        txfSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO to Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txfSearch.setPreferredSize(new java.awt.Dimension(500, 100));
        txfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchActionPerformed(evt);
            }
        });
        jPanel3.add(txfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 440, 90));

        jButton2.setBackground(new java.awt.Color(0, 193, 212));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDrop.png"))); // NOI18N
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 100, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoMenu;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrorCategory;
    private javax.swing.JLabel lblErrorIMO;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorQuantity;
    private javax.swing.JLabel lblErrorType;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JTextField txfIMO;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfQuantity;
    private javax.swing.JTextField txfSearch;
    // End of variables declaration//GEN-END:variables
}
