package View;

import javax.swing.JButton;

/**
 *
 * @author Manfred Armijos
 */
public class ViewDock extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewDock() {
        initComponents();
        setUndecorated(true);
        setLocationRelativeTo(null);
    }

    public JButton getBtnGoMenu() {
        return btnBack;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblServImo6 = new javax.swing.JLabel();
        lblServImo1 = new javax.swing.JLabel();
        lblServImo = new javax.swing.JLabel();
        lblServImo3 = new javax.swing.JLabel();
        lblServImo2 = new javax.swing.JLabel();
        lblServImo5 = new javax.swing.JLabel();
        lblServImo4 = new javax.swing.JLabel();
        rbtLoading = new javax.swing.JRadioButton();
        rbtUnloading = new javax.swing.JRadioButton();
        chbRefuel = new javax.swing.JCheckBox();
        chbMaintenance = new javax.swing.JCheckBox();
        chbClean = new javax.swing.JCheckBox();
        btnUpdate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDelCollection = new javax.swing.JButton();
        btnDelDB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(10, 107, 207));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconBack.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setFocusable(false);
        btnBack.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, -1, -1));

        btnCreate.setBorder(null);
        btnCreate.setBorderPainted(false);
        btnCreate.setContentAreaFilled(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, 160));

        lblServImo6.setBackground(new java.awt.Color(255, 255, 255));
        lblServImo6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblServImo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServImo6.setText("daw");
        jPanel1.add(lblServImo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, 45));

        lblServImo1.setBackground(new java.awt.Color(255, 255, 255));
        lblServImo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblServImo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServImo1.setText("daw");
        jPanel1.add(lblServImo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 45));

        lblServImo.setBackground(new java.awt.Color(255, 255, 255));
        lblServImo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblServImo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServImo.setText("daw");
        jPanel1.add(lblServImo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, 45));

        lblServImo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo3.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo3.setText("0");
        lblServImo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Subtotal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lblServImo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 300, 70));

        lblServImo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo2.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo2.setText("0");
        lblServImo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Total", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lblServImo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 300, 70));

        lblServImo5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo5.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo5.setText("0");
        lblServImo5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "IVA", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lblServImo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 300, 70));

        lblServImo4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo4.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo4.setText("0");
        lblServImo4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Discount", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lblServImo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 70));

        rbtLoading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtLoading.setForeground(new java.awt.Color(255, 255, 255));
        rbtLoading.setText("Loading");
        rbtLoading.setContentAreaFilled(false);
        jPanel1.add(rbtLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        rbtUnloading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtUnloading.setForeground(new java.awt.Color(255, 255, 255));
        rbtUnloading.setText("Unloading");
        rbtUnloading.setContentAreaFilled(false);
        jPanel1.add(rbtUnloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        chbRefuel.setBackground(new java.awt.Color(102, 153, 255));
        chbRefuel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbRefuel.setForeground(new java.awt.Color(255, 255, 255));
        chbRefuel.setText("Refuel");
        chbRefuel.setContentAreaFilled(false);
        chbRefuel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbRefuel.setFocusPainted(false);
        jPanel1.add(chbRefuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        chbMaintenance.setBackground(new java.awt.Color(102, 153, 255));
        chbMaintenance.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbMaintenance.setForeground(new java.awt.Color(255, 255, 255));
        chbMaintenance.setText("Maintenance");
        chbMaintenance.setContentAreaFilled(false);
        chbMaintenance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbMaintenance.setFocusPainted(false);
        jPanel1.add(chbMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, -1, -1));

        chbClean.setBackground(new java.awt.Color(102, 153, 255));
        chbClean.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbClean.setForeground(new java.awt.Color(255, 255, 255));
        chbClean.setText("Clean");
        chbClean.setContentAreaFilled(false);
        chbClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbClean.setFocusPainted(false);
        jPanel1.add(chbClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, -1, -1));

        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 100, 50));

        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setContentAreaFilled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 285, 100, 50));

        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 285, 100, 50));

        btnDelCollection.setBorder(null);
        btnDelCollection.setBorderPainted(false);
        btnDelCollection.setContentAreaFilled(false);
        btnDelCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCollectionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelCollection, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 285, 100, 50));

        btnDelDB.setBorder(null);
        btnDelDB.setBorderPainted(false);
        btnDelDB.setContentAreaFilled(false);
        btnDelDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1147, 285, 100, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "IMO", "Name", "Type", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 880, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDock.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDelCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCollectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelCollectionActionPerformed

    private void btnDelDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelDBActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelCollection;
    private javax.swing.JButton btnDelDB;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chbClean;
    private javax.swing.JCheckBox chbMaintenance;
    private javax.swing.JCheckBox chbRefuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblServImo;
    private javax.swing.JLabel lblServImo1;
    private javax.swing.JLabel lblServImo2;
    private javax.swing.JLabel lblServImo3;
    private javax.swing.JLabel lblServImo4;
    private javax.swing.JLabel lblServImo5;
    private javax.swing.JLabel lblServImo6;
    private javax.swing.JRadioButton rbtLoading;
    private javax.swing.JRadioButton rbtUnloading;
    // End of variables declaration//GEN-END:variables
}
