package View;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manfred Armijos
 */
public class ViewPort extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewPort() {
        initComponents();
    }

    public JButton getBtnGoMenu() {
        return btnGoMenu;
    }

    public JButton getBtnSave() {
        return btnSave;
    }
    
    
    public void loadDataToTable(ArrayList<Object[]> data) {
        
        DefaultTableModel tableModel = (DefaultTableModel) tblVesselQueue.getModel();
        
        tableModel.setRowCount(0);
        
        for(Object[] row : data) {
            tableModel.addRow(row);
        }
    }
    
    /*
    SHOW ERRORS
    */
    
    public void showErrorCategory(String error) {
        lblErrorCategory.setText(error);
    }

    public void showlErrorName(String error) {
        lblErrorName.setText(error);
    }
    
    public void showlErrorIMO(String error) {
        lblErrorIMO.setText(error);
    }

    public void showErrorQuantity(String error) {
        lblErrorOccupancy.setText(error);
    }

    public void showErrorType(String error) {
        lblErrorType.setText(error);
    }
    
    /*
    CLEAN ERRORS
    */
       
    public void cleanErrorCategory() {
        lblErrorCategory.setText("");
    }

    public void cleanlErrorName() {
        lblErrorName.setText("");
    }
    
    public void cleanlErrorIMO() {
        lblErrorIMO.setText("");
    }

    public void cleanErrorQuantity() {
        lblErrorOccupancy.setText("");
    }

    public void cleanErrorType() {
        lblErrorType.setText("");
    }
    

    public String getIMOForm() {
        return txfIMO.getText();
    }

    public String getNameForm() {
        return txfName.getText();
    }

    public String getSearchForm() {
        return txfSearch.getText();
    }

    public int getOccupancyForm() {
        return sldOccupancy.getValue();
    }
    
    public String getTypeForm() {
        return cbxType.getSelectedItem().toString();
    }
    
    public String getCategoryForm() {
        return cbxCategory.getSelectedItem().toString();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txfName = new javax.swing.JTextField();
        lblErrorName = new javax.swing.JLabel();
        lblErrorCategory = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        cbxType = new javax.swing.JComboBox<>();
        txfIMO = new javax.swing.JTextField();
        lblErrorIMO = new javax.swing.JLabel();
        lblErrorType = new javax.swing.JLabel();
        lblErrorOccupancy = new javax.swing.JLabel();
        sldOccupancy = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVesselQueue = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnGoMenu = new javax.swing.JButton();
        txfSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblFormTitle.setText("VESSEL FORM");
        jPanel2.add(lblFormTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnSave.setBackground(new java.awt.Color(0, 193, 212));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSave.setText("SAVE");
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 200, 50));

        txfName.setBackground(new java.awt.Color(30, 40, 53));
        txfName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName.setForeground(new java.awt.Color(255, 255, 255));
        txfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(txfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 410, -1));

        lblErrorName.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 330, 20));

        lblErrorCategory.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 330, 20));

        cbxCategory.setBackground(new java.awt.Color(30, 40, 53));
        cbxCategory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxCategory.setForeground(new java.awt.Color(255, 255, 255));
        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "SMALL", "MEDIUM", "LARGE", "EXTRALARGE" }));
        cbxCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxCategory.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxCategory.setFocusable(false);
        cbxCategory.setPreferredSize(new java.awt.Dimension(500, 55));
        jPanel2.add(cbxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 410, -1));

        cbxType.setBackground(new java.awt.Color(30, 40, 53));
        cbxType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxType.setForeground(new java.awt.Color(255, 255, 255));
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "CRUISE", "CONTAINER" }));
        cbxType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxType.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxType.setFocusable(false);
        cbxType.setPreferredSize(new java.awt.Dimension(500, 55));
        jPanel2.add(cbxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 410, -1));

        txfIMO.setBackground(new java.awt.Color(30, 40, 53));
        txfIMO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfIMO.setForeground(new java.awt.Color(255, 255, 255));
        txfIMO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfIMO.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfIMO.setCaretColor(new java.awt.Color(255, 255, 255));
        txfIMO.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(txfIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 410, -1));

        lblErrorIMO.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorIMO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErrorIMO.setToolTipText("");
        jPanel2.add(lblErrorIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 330, 20));

        lblErrorType.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 330, 20));

        lblErrorOccupancy.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorOccupancy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblErrorOccupancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 330, 20));

        sldOccupancy.setBackground(new java.awt.Color(30, 40, 53));
        sldOccupancy.setForeground(new java.awt.Color(255, 255, 255));
        sldOccupancy.setMajorTickSpacing(10);
        sldOccupancy.setMinorTickSpacing(5);
        sldOccupancy.setPaintLabels(true);
        sldOccupancy.setPaintTicks(true);
        sldOccupancy.setSnapToTicks(true);
        sldOccupancy.setToolTipText("");
        sldOccupancy.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Occupancy  %", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        sldOccupancy.setFocusable(false);
        jPanel2.add(sldOccupancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 410, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 450, 640));

        jPanel3.setBackground(new java.awt.Color(30, 40, 53));
        jPanel3.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVesselQueue.setBackground(new java.awt.Color(30, 40, 53));
        tblVesselQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IMO", "Name", "Type", "Category", "Occupancy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVesselQueue);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 720, 290));

        jButton1.setBackground(new java.awt.Color(0, 193, 212));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconSearch.png"))); // NOI18N
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, 70));

        jButton3.setBackground(new java.awt.Color(0, 193, 212));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconUpdate.png"))); // NOI18N
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 70));

        jButton4.setBackground(new java.awt.Color(0, 193, 212));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDelete.png"))); // NOI18N
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 100, 70));

        jButton5.setBackground(new java.awt.Color(0, 193, 212));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconClear.png"))); // NOI18N
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 70));

        btnGoMenu.setBackground(new java.awt.Color(10, 107, 207));
        btnGoMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconExit.png"))); // NOI18N
        btnGoMenu.setBorderPainted(false);
        btnGoMenu.setContentAreaFilled(false);
        jPanel3.add(btnGoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 80, 40));

        txfSearch.setBackground(new java.awt.Color(30, 40, 53));
        txfSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfSearch.setForeground(new java.awt.Color(255, 255, 255));
        txfSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO to Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txfSearch.setPreferredSize(new java.awt.Dimension(500, 100));
        txfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSearchActionPerformed(evt);
            }
        });
        jPanel3.add(txfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 440, 90));

        jButton2.setBackground(new java.awt.Color(0, 193, 212));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDrop.png"))); // NOI18N
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 100, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 740, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoMenu;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorCategory;
    private javax.swing.JLabel lblErrorIMO;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorOccupancy;
    private javax.swing.JLabel lblErrorType;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JSlider sldOccupancy;
    private javax.swing.JTable tblVesselQueue;
    private javax.swing.JTextField txfIMO;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfSearch;
    // End of variables declaration//GEN-END:variables
}
