package View;

import javax.swing.JButton;

/**
 *
 * @author Manfred Armijos
 */
public class ViewDock extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewDock() {
        initComponents();
    }

    public JButton getBtnGoMenu() {
        return btnGoMenu;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlDock = new javax.swing.JPanel();
        lblServImo = new javax.swing.JLabel();
        btnDock = new javax.swing.JButton();
        lblErrorDock = new javax.swing.JLabel();
        lblServImo1 = new javax.swing.JLabel();
        pnlOperation = new javax.swing.JPanel();
        lblOperation = new javax.swing.JLabel();
        btnOperation = new javax.swing.JButton();
        rbtLoading = new javax.swing.JRadioButton();
        rbtUnloading = new javax.swing.JRadioButton();
        lblExtras = new javax.swing.JLabel();
        chbRefuel = new javax.swing.JCheckBox();
        chbMaintenance = new javax.swing.JCheckBox();
        chbClean = new javax.swing.JCheckBox();
        pnlPayment = new javax.swing.JPanel();
        btnBilling = new javax.swing.JButton();
        lblServImo2 = new javax.swing.JLabel();
        lblServImo3 = new javax.swing.JLabel();
        lblServImo4 = new javax.swing.JLabel();
        lblServImo5 = new javax.swing.JLabel();
        lblPayment1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblPayment = new javax.swing.JLabel();
        btnGoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDock.setBackground(new java.awt.Color(30, 40, 53));
        pnlDock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServImo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo.setForeground(new java.awt.Color(189, 195, 199));
        lblServImo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "IMO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDock.add(lblServImo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 300, 80));

        btnDock.setBackground(new java.awt.Color(10, 107, 207));
        btnDock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDock.setText("Dock");
        btnDock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDockActionPerformed(evt);
            }
        });
        pnlDock.add(btnDock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 110));

        lblErrorDock.setForeground(new java.awt.Color(255, 158, 0));
        pnlDock.add(lblErrorDock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, -1));

        lblServImo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo1.setForeground(new java.awt.Color(189, 195, 199));
        lblServImo1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Type", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDock.add(lblServImo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 300, 80));

        jPanel1.add(pnlDock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 850, 150));

        pnlOperation.setBackground(new java.awt.Color(30, 40, 53));
        pnlOperation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOperation.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblOperation.setForeground(new java.awt.Color(189, 195, 199));
        lblOperation.setText("Operation");
        pnlOperation.add(lblOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnOperation.setBackground(new java.awt.Color(10, 107, 207));
        btnOperation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnOperation.setText("Operate");
        btnOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperationActionPerformed(evt);
            }
        });
        pnlOperation.add(btnOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 50));

        rbtLoading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtLoading.setForeground(new java.awt.Color(255, 255, 255));
        rbtLoading.setText("Loading");
        rbtLoading.setContentAreaFilled(false);
        pnlOperation.add(rbtLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        rbtUnloading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtUnloading.setForeground(new java.awt.Color(255, 255, 255));
        rbtUnloading.setText("Unloading");
        rbtUnloading.setContentAreaFilled(false);
        pnlOperation.add(rbtUnloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lblExtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExtras.setForeground(new java.awt.Color(255, 255, 255));
        lblExtras.setText("Extras");
        pnlOperation.add(lblExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        chbRefuel.setBackground(new java.awt.Color(102, 153, 255));
        chbRefuel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbRefuel.setForeground(new java.awt.Color(255, 255, 255));
        chbRefuel.setText("Refuel");
        chbRefuel.setContentAreaFilled(false);
        chbRefuel.setFocusPainted(false);
        pnlOperation.add(chbRefuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        chbMaintenance.setBackground(new java.awt.Color(102, 153, 255));
        chbMaintenance.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbMaintenance.setForeground(new java.awt.Color(255, 255, 255));
        chbMaintenance.setText("Maintenance");
        chbMaintenance.setContentAreaFilled(false);
        chbMaintenance.setFocusPainted(false);
        pnlOperation.add(chbMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        chbClean.setBackground(new java.awt.Color(102, 153, 255));
        chbClean.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chbClean.setForeground(new java.awt.Color(255, 255, 255));
        chbClean.setText("Clean");
        chbClean.setContentAreaFilled(false);
        chbClean.setFocusPainted(false);
        pnlOperation.add(chbClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jPanel1.add(pnlOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 470));

        pnlPayment.setBackground(new java.awt.Color(30, 40, 53));
        pnlPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBilling.setBackground(new java.awt.Color(10, 107, 207));
        btnBilling.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBilling.setText("Bill");
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        pnlPayment.add(btnBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 200, 50));

        lblServImo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo2.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo2.setText("0");
        lblServImo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Total", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlPayment.add(lblServImo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 70));

        lblServImo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo3.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo3.setText("0");
        lblServImo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Subtotal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlPayment.add(lblServImo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, 70));

        lblServImo4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo4.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo4.setText("0");
        lblServImo4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Discount", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlPayment.add(lblServImo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 70));

        lblServImo5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblServImo5.setForeground(new java.awt.Color(255, 255, 255));
        lblServImo5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServImo5.setText("0");
        lblServImo5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblServImo5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "IVA", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlPayment.add(lblServImo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 300, 70));

        lblPayment1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPayment1.setForeground(new java.awt.Color(189, 195, 199));
        lblPayment1.setText("Payment");
        pnlPayment.add(lblPayment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel1.add(pnlPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 320, 470));

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(30, 40, 53));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 590, 290));

        jButton3.setBackground(new java.awt.Color(0, 193, 212));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconUpdate.png"))); // NOI18N
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 70));

        jButton4.setBackground(new java.awt.Color(0, 193, 212));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDelete.png"))); // NOI18N
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 70));

        jButton5.setBackground(new java.awt.Color(0, 193, 212));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconClear.png"))); // NOI18N
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 100, 70));

        jButton2.setBackground(new java.awt.Color(0, 193, 212));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDrop.png"))); // NOI18N
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 100, 70));

        lblPayment.setBackground(new java.awt.Color(255, 255, 255));
        lblPayment.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(189, 195, 199));
        lblPayment.setText("Payment");
        jPanel2.add(lblPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 610, 470));

        btnGoMenu.setBackground(new java.awt.Color(10, 107, 207));
        btnGoMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconExit.png"))); // NOI18N
        btnGoMenu.setContentAreaFilled(false);
        jPanel1.add(btnGoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDockActionPerformed
        //getPort().dockVessel();
    }//GEN-LAST:event_btnDockActionPerformed

    private void btnOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperationActionPerformed
        //getPort().operations();
    }//GEN-LAST:event_btnOperationActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        //getPort().bill();
    }//GEN-LAST:event_btnBillingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnDock;
    private javax.swing.JButton btnGoMenu;
    private javax.swing.JButton btnOperation;
    private javax.swing.JCheckBox chbClean;
    private javax.swing.JCheckBox chbMaintenance;
    private javax.swing.JCheckBox chbRefuel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrorDock;
    private javax.swing.JLabel lblExtras;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPayment1;
    private javax.swing.JLabel lblServImo;
    private javax.swing.JLabel lblServImo1;
    private javax.swing.JLabel lblServImo2;
    private javax.swing.JLabel lblServImo3;
    private javax.swing.JLabel lblServImo4;
    private javax.swing.JLabel lblServImo5;
    private javax.swing.JPanel pnlDock;
    private javax.swing.JPanel pnlOperation;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JRadioButton rbtLoading;
    private javax.swing.JRadioButton rbtUnloading;
    // End of variables declaration//GEN-END:variables
}
