package View;

import javax.swing.JButton;

/**
 *
 * @author Manfred Armijos
 */
public class ViewPort extends javax.swing.JFrame {

    /**
     * Creates new form Plantilla
     */
    public ViewPort() {
        initComponents();
    }

    public JButton getBtnGoMenu() {
        return btnGoMenu;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        btnForm = new javax.swing.JButton();
        txfName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txfName4 = new javax.swing.JTextField();
        cbxType = new javax.swing.JComboBox<>();
        txfName5 = new javax.swing.JTextField();
        cbxType1 = new javax.swing.JComboBox<>();
        txfName6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnGoMenu = new javax.swing.JButton();
        txfName2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 20, 25));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 40, 53));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblFormTitle.setText("VESSEL FORM");
        jPanel2.add(lblFormTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        btnForm.setBackground(new java.awt.Color(0, 193, 212));
        btnForm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnForm.setText("Next");
        btnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormActionPerformed(evt);
            }
        });
        jPanel2.add(btnForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 200, 50));

        txfName.setBackground(new java.awt.Color(30, 40, 53));
        txfName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName.setForeground(new java.awt.Color(255, 255, 255));
        txfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName.setPreferredSize(new java.awt.Dimension(500, 75));
        txfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNameActionPerformed(evt);
            }
        });
        jPanel2.add(txfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 100, 20));

        txfName4.setBackground(new java.awt.Color(30, 40, 53));
        txfName4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName4.setForeground(new java.awt.Color(255, 255, 255));
        txfName4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName4.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName4.setPreferredSize(new java.awt.Dimension(500, 75));
        txfName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName4ActionPerformed(evt);
            }
        });
        jPanel2.add(txfName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        cbxType.setBackground(new java.awt.Color(30, 40, 53));
        cbxType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxType.setForeground(new java.awt.Color(255, 255, 255));
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "CRUISE", "CONTAINER" }));
        cbxType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxType.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxType.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(cbxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txfName5.setBackground(new java.awt.Color(30, 40, 53));
        txfName5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName5.setForeground(new java.awt.Color(255, 255, 255));
        txfName5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName5.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName5.setPreferredSize(new java.awt.Dimension(500, 75));
        txfName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName5ActionPerformed(evt);
            }
        });
        jPanel2.add(txfName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        cbxType1.setBackground(new java.awt.Color(30, 40, 53));
        cbxType1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxType1.setForeground(new java.awt.Color(255, 255, 255));
        cbxType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "CRUISE", "CONTAINER" }));
        cbxType1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxType1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbxType1.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(cbxType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txfName6.setBackground(new java.awt.Color(30, 40, 53));
        txfName6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName6.setForeground(new java.awt.Color(255, 255, 255));
        txfName6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName6.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName6.setPreferredSize(new java.awt.Dimension(500, 75));
        txfName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName6ActionPerformed(evt);
            }
        });
        jPanel2.add(txfName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 100, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 640));

        jPanel3.setBackground(new java.awt.Color(30, 40, 53));
        jPanel3.setPreferredSize(new java.awt.Dimension(610, 610));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(30, 40, 53));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 590, 290));

        jButton1.setBackground(new java.awt.Color(0, 193, 212));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconSearch.png"))); // NOI18N
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, 70));

        jButton3.setBackground(new java.awt.Color(0, 193, 212));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconUpdate.png"))); // NOI18N
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 70));

        jButton4.setBackground(new java.awt.Color(0, 193, 212));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDelete.png"))); // NOI18N
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 70));

        jButton5.setBackground(new java.awt.Color(0, 193, 212));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconClear.png"))); // NOI18N
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, 70));

        btnGoMenu.setBackground(new java.awt.Color(10, 107, 207));
        btnGoMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconExit.png"))); // NOI18N
        btnGoMenu.setBorderPainted(false);
        btnGoMenu.setContentAreaFilled(false);
        jPanel3.add(btnGoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 80, 40));

        txfName2.setBackground(new java.awt.Color(30, 40, 53));
        txfName2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfName2.setForeground(new java.awt.Color(255, 255, 255));
        txfName2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfName2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "IMO to Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        txfName2.setCaretColor(new java.awt.Color(255, 255, 255));
        txfName2.setPreferredSize(new java.awt.Dimension(500, 100));
        txfName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfName2ActionPerformed(evt);
            }
        });
        jPanel3.add(txfName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 440, 90));

        jButton2.setBackground(new java.awt.Color(0, 193, 212));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconDrop.png"))); // NOI18N
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 100, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormActionPerformed
    }//GEN-LAST:event_btnFormActionPerformed

    private void txfName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName2ActionPerformed

    private void txfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameActionPerformed

    private void txfName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName4ActionPerformed

    private void txfName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName5ActionPerformed

    private void txfName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfName6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForm;
    private javax.swing.JButton btnGoMenu;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JComboBox<String> cbxType1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfName2;
    private javax.swing.JTextField txfName4;
    private javax.swing.JTextField txfName5;
    private javax.swing.JTextField txfName6;
    // End of variables declaration//GEN-END:variables
}
